/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Message */
        post: operations["submit_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/confirm-formula": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Formula */
        post: operations["confirm_formula_api_sessions__session_id__confirm_formula_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/field-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Fields */
        post: operations["search_fields_api_sessions__session_id__field_candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/confirm-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Fields */
        post: operations["confirm_fields_api_sessions__session_id__confirm_fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Manifest */
        post: operations["build_manifest_api_sessions__session_id__manifest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/revise-formula": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Formula */
        post: operations["revise_formula_api_sessions__session_id__revise_formula_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/revise-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Fields */
        post: operations["revise_fields_api_sessions__session_id__revise_fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/revise-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Request */
        post: operations["revise_request_api_sessions__session_id__revise_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Execution */
        post: operations["cancel_execution_api_sessions__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Session */
        post: operations["clone_session_api_sessions__session_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Session Events
         * @description Stream session events, resuming after ``Last-Event-ID`` when supplied.
         *
         *     ``replay_only`` returns the backlog and closes, which is what a client that
         *     just wants to catch up needs — and what makes this testable without a
         *     connection that never ends.
         */
        get: operations["stream_session_events_api_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Ambiguity
         * @description An unresolved choice persisted on a FactorSpec (e.g. missing rebalance).
         */
        Ambiguity: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Field */
            field: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Options */
            options?: string[];
            /** Recommended */
            recommended?: string | null;
            /**
             * Blocking
             * @default false
             */
            blocking: boolean;
        };
        /**
         * AnnouncementTimingPolicy
         * @description What to assume when the publication moment is unknown.
         *
         *     ``conservative`` defers to the next session, which is the only choice that
         *     cannot manufacture look-ahead.
         * @enum {string}
         */
        AnnouncementTimingPolicy: "conservative" | "as_reported";
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: "all" | "stock" | "index" | "fund" | "bond" | "futures" | "options";
        /** BuildBody */
        BuildBody: {
            /** Expected Version */
            expected_version: number;
            request: components["schemas"]["ResearchRequest"];
        };
        /** CandidatesBody */
        CandidatesBody: {
            /** Expected Version */
            expected_version: number;
            /** Candidates */
            candidates?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ClarificationQuestion
         * @description A question presented to the user, possibly blocking further progress.
         */
        ClarificationQuestion: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Question Id */
            question_id: string;
            /** Question */
            question: string;
            /** Field */
            field?: string | null;
            /** Options */
            options?: string[];
            /** Recommended */
            recommended?: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Blocking
             * @default false
             */
            blocking: boolean;
            /**
             * Target Version
             * @default 1
             */
            target_version: number;
        };
        /** CloneBody */
        CloneBody: {
            /** New Session Id */
            new_session_id: string;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** CreateSessionBody */
        CreateSessionBody: {
            /** Session Id */
            session_id: string;
        };
        /**
         * DataRequirement
         * @description A single logical variable needed by a factor, with its data semantics.
         */
        DataRequirement: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Logical Name */
            logical_name: string;
            /**
             * Meaning
             * @default
             */
            meaning: string;
            asset_type?: components["schemas"]["AssetType"] | null;
            frequency?: components["schemas"]["Frequency"] | null;
            /** Unit */
            unit?: string | null;
            /**
             * Point In Time Required
             * @default false
             */
            point_in_time_required: boolean;
            /** Financial Period */
            financial_period?: string | null;
            /**
             * Announcement Date Required
             * @default false
             */
            announcement_date_required: boolean;
        };
        /**
         * DataRules
         * @description Universe and data-selection rules.
         *
         *     These were never transforms and are unaffected by ordering, so they stay as
         *     plain switches. The transform switches that used to live alongside them now
         *     belong to :class:`PreprocessingPipeline`.
         */
        DataRules: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Use Adjusted Price
             * @default true
             */
            use_adjusted_price: boolean;
            /**
             * Exclude St
             * @default true
             */
            exclude_st: boolean;
            /**
             * Exclude Suspended
             * @default true
             */
            exclude_suspended: boolean;
            /**
             * Min Listed Days
             * @default 0
             */
            min_listed_days: number;
        };
        /**
         * ErrorCategory
         * @enum {string}
         */
        ErrorCategory: "input" | "field" | "empty_data" | "time_basis" | "formula" | "resource" | "infrastructure";
        /**
         * ExecutionPlan
         * @description An ordered, fully-determined retrieval plan.
         *
         *     Carries its own ``time_convention`` rather than reading it back from the spec:
         *     the plan is what gets signed, queued and replayed, so the timing rules that
         *     decide when a signal is knowable have to travel with it.
         */
        ExecutionPlan: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Steps */
            steps?: components["schemas"]["ExecutionStep"][];
            /** Warmup Start */
            warmup_start?: string | null;
            time_convention?: components["schemas"]["TimeConvention"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExecutionPrice
         * @enum {string}
         */
        ExecutionPrice: "NEXT_OPEN" | "NEXT_CLOSE" | "VWAP" | "NONE";
        /** ExecutionResult */
        ExecutionResult: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            status: components["schemas"]["ExecutionStatus"];
            /** Artifact Uri */
            artifact_uri?: string | null;
            data_validation?: components["schemas"]["ValidationReport"] | null;
            formula_validation?: components["schemas"]["ValidationReport"] | null;
            result_validation?: components["schemas"]["ValidationReport"] | null;
            /**
             * Log Summary
             * @default
             */
            log_summary: string;
            /** Resource Stats */
            resource_stats?: {
                [key: string]: unknown;
            };
            /** Errors */
            errors?: components["schemas"]["StructuredError"][];
            /** Revision Suggestion */
            revision_suggestion?: string | null;
        };
        /**
         * ExecutionStatus
         * @enum {string}
         */
        ExecutionStatus: "pending" | "running" | "completed" | "failed";
        /**
         * ExecutionStep
         * @description One deterministic retrieval/computation step (tool + bounded arguments).
         */
        ExecutionStep: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Tool */
            tool: string;
            /**
             * Purpose
             * @default
             */
            purpose: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Inputs */
            inputs?: string[];
            /** Output Schema */
            output_schema?: {
                [key: string]: unknown;
            } | null;
            /** Postprocessing */
            postprocessing?: {
                [key: string]: unknown;
            } | null;
            /** Validation */
            validation?: string[];
            /**
             * Failure Strategy
             * @default fail
             */
            failure_strategy: string;
        };
        /**
         * FactorDirection
         * @enum {string}
         */
        FactorDirection: "higher_is_better" | "lower_is_better" | "neutral";
        /**
         * FactorSpec
         * @description The confirmed, machine-checkable description of one factor.
         *
         *     ``formula_ast`` is the single source of truth. ``canonical_formula`` is
         *     rendered from it by the backend and is what the user actually confirms;
         *     ``formula_explanation`` is the model's prose and is display-only. The model
         *     never authors the confirmed formula, so what is signed off and what is
         *     executed cannot diverge.
         */
        "FactorSpec-Input": {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Factor Name */
            factor_name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            asset_type: components["schemas"]["AssetType"];
            /** Universe */
            universe: string;
            frequency: components["schemas"]["Frequency"];
            rebalance_frequency?: components["schemas"]["Frequency"] | null;
            direction?: components["schemas"]["FactorDirection"] | null;
            formula_ast: components["schemas"]["FormulaNode-Input"];
            /**
             * Canonical Formula
             * @default
             */
            canonical_formula: string;
            /**
             * Formula Explanation
             * @default
             */
            formula_explanation: string;
            /** Variables */
            variables?: components["schemas"]["DataRequirement"][];
            data_rules?: components["schemas"]["DataRules"];
            preprocessing?: components["schemas"]["PreprocessingPipeline"];
            time_convention?: components["schemas"]["TimeConvention"];
            /** Ambiguities */
            ambiguities?: components["schemas"]["Ambiguity"][];
            /** Source Evidence */
            source_evidence?: components["schemas"]["ReportEvidence"][];
        };
        /**
         * FactorSpec
         * @description The confirmed, machine-checkable description of one factor.
         *
         *     ``formula_ast`` is the single source of truth. ``canonical_formula`` is
         *     rendered from it by the backend and is what the user actually confirms;
         *     ``formula_explanation`` is the model's prose and is display-only. The model
         *     never authors the confirmed formula, so what is signed off and what is
         *     executed cannot diverge.
         */
        "FactorSpec-Output": {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Factor Name */
            factor_name: string;
            /**
             * Hypothesis
             * @default
             */
            hypothesis: string;
            asset_type: components["schemas"]["AssetType"];
            /** Universe */
            universe: string;
            frequency: components["schemas"]["Frequency"];
            rebalance_frequency?: components["schemas"]["Frequency"] | null;
            direction?: components["schemas"]["FactorDirection"] | null;
            formula_ast: components["schemas"]["FormulaNode-Output"];
            /**
             * Canonical Formula
             * @default
             */
            canonical_formula: string;
            /**
             * Formula Explanation
             * @default
             */
            formula_explanation: string;
            /** Variables */
            variables?: components["schemas"]["DataRequirement"][];
            data_rules?: components["schemas"]["DataRules"];
            preprocessing?: components["schemas"]["PreprocessingPipeline"];
            time_convention?: components["schemas"]["TimeConvention"];
            /** Ambiguities */
            ambiguities?: components["schemas"]["Ambiguity"][];
            /** Source Evidence */
            source_evidence?: components["schemas"]["ReportEvidence"][];
        };
        /**
         * FieldSelection
         * @description A user-confirmed mapping from a logical variable to a concrete Wind field.
         */
        FieldSelection: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Logical Name */
            logical_name: string;
            /** Table */
            table: string;
            /** Field */
            field: string;
            time_role?: components["schemas"]["FieldTimeRole"] | null;
            /**
             * Point In Time
             * @default false
             */
            point_in_time: boolean;
            /** Announcement Date Field */
            announcement_date_field?: string | null;
            /** Report Period Field */
            report_period_field?: string | null;
        };
        /**
         * FieldTimeRole
         * @description How a field's timestamp is interpreted for point-in-time correctness.
         * @enum {string}
         */
        FieldTimeRole: "observation" | "announcement" | "report_period" | "as_of";
        /** FieldsBody */
        FieldsBody: {
            /** Expected Version */
            expected_version: number;
            /** Field Selections */
            field_selections?: components["schemas"]["FieldSelection"][];
        };
        /**
         * FormulaNode
         * @description A single node in the factor formula AST.
         *
         *     Shapes (mutually exclusive, enforced):
         *       * ``variable`` -- references a confirmed data variable by ``name``;
         *       * ``literal``  -- a numeric constant ``value``;
         *       * ``call``     -- applies a registered ``op`` to ``args`` with optional ``params``.
         */
        "FormulaNode-Input": {
            /**
             * Type
             * @enum {string}
             */
            type: "variable" | "literal" | "call";
            /** Name */
            name?: string | null;
            /** Value */
            value?: number | null;
            /** Op */
            op?: ("add" | "subtract" | "multiply" | "divide" | "negative" | "log" | "rank" | "rolling_return" | "rolling_std" | "rolling_mean" | "fillna") | null;
            /** Args */
            args?: components["schemas"]["FormulaNode-Input"][];
            /** Params */
            params?: {
                [key: string]: number | string;
            };
        };
        /**
         * FormulaNode
         * @description A single node in the factor formula AST.
         *
         *     Shapes (mutually exclusive, enforced):
         *       * ``variable`` -- references a confirmed data variable by ``name``;
         *       * ``literal``  -- a numeric constant ``value``;
         *       * ``call``     -- applies a registered ``op`` to ``args`` with optional ``params``.
         */
        "FormulaNode-Output": {
            /**
             * Type
             * @enum {string}
             */
            type: "variable" | "literal" | "call";
            /** Name */
            name?: string | null;
            /** Value */
            value?: number | null;
            /** Op */
            op?: ("add" | "subtract" | "multiply" | "divide" | "negative" | "log" | "rank" | "rolling_return" | "rolling_std" | "rolling_mean" | "fillna") | null;
            /** Args */
            args?: components["schemas"]["FormulaNode-Output"][];
            /** Params */
            params?: {
                [key: string]: number | string;
            };
        };
        /**
         * Frequency
         * @enum {string}
         */
        Frequency: "daily" | "weekly" | "monthly" | "quarterly" | "yearly";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
        };
        /**
         * InformationAvailableTime
         * @description When a researcher could actually have known the value.
         * @enum {string}
         */
        InformationAvailableTime: "T_INTRADAY" | "T_AFTER_CLOSE" | "ANNOUNCEMENT_BEFORE_OPEN" | "ANNOUNCEMENT_AFTER_CLOSE";
        /** MessageBody */
        MessageBody: {
            /** Expected Version */
            expected_version: number;
            request: components["schemas"]["ResearchRequest"];
        };
        /**
         * ObservationTime
         * @description When the underlying datum is stamped.
         * @enum {string}
         */
        ObservationTime: "T_OPEN" | "T_CLOSE" | "REPORT_PERIOD";
        /**
         * PreprocessingOperation
         * @enum {string}
         */
        PreprocessingOperation: "winsorize" | "zscore" | "industry_neutralize" | "fillna";
        /**
         * PreprocessingPipeline
         * @description An ordered, duplicate-free sequence of transforms.
         */
        PreprocessingPipeline: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Steps */
            steps?: components["schemas"]["PreprocessingStep"][];
        };
        /** PreprocessingStep */
        PreprocessingStep: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Order */
            order: number;
            operation: components["schemas"]["PreprocessingOperation"];
            target: components["schemas"]["PreprocessingTarget"];
            /** Method */
            method?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: number | string;
            };
        };
        /**
         * PreprocessingTarget
         * @description What a step operates on.
         *
         *     ``variables`` runs before the formula, once per raw input; ``factor`` runs
         *     after the formula, on its single output. This distinction is precisely what
         *     a boolean switch could not express.
         * @enum {string}
         */
        PreprocessingTarget: "variables" | "factor";
        /**
         * ReportEvidence
         * @description A piece of source text that justifies an extracted value.
         */
        ReportEvidence: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Page Number */
            page_number?: number | null;
            /**
             * Quote
             * @default
             */
            quote: string;
            /** Language */
            language?: string | null;
            /** Formula Context */
            formula_context?: string | null;
            /** Confidence */
            confidence?: number | null;
            /**
             * Source
             * @default text
             */
            source: string;
        };
        /**
         * ResearchRequest
         * @description A user's natural-language research idea plus its evaluation envelope.
         */
        ResearchRequest: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            asset_type: components["schemas"]["AssetType"];
            /** Universe */
            universe: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /** Research Idea */
            research_idea: string;
            /**
             * Language
             * @default zh
             */
            language: string;
            /** @default daily */
            frequency: components["schemas"]["Frequency"];
            direction?: components["schemas"]["FactorDirection"] | null;
            /** Report Artifact Id */
            report_artifact_id?: string | null;
            data_rules?: components["schemas"]["DataRules"];
            preprocessing?: components["schemas"]["PreprocessingPipeline"];
            time_convention?: components["schemas"]["TimeConvention"];
        };
        /**
         * SessionSnapshot
         * @description The folded, current state of a session, fully derivable from its events.
         */
        SessionSnapshot: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Session Id */
            session_id: string;
            /** State */
            state: string;
            /** Version */
            version: number;
            request?: components["schemas"]["ResearchRequest"] | null;
            factor_spec?: components["schemas"]["FactorSpec-Output"] | null;
            /** Field Selections */
            field_selections?: components["schemas"]["FieldSelection"][];
            plan?: components["schemas"]["ExecutionPlan"] | null;
            /** Generated Code */
            generated_code?: string | null;
            /** Code Sha256 */
            code_sha256?: string | null;
            execution_result?: components["schemas"]["ExecutionResult"] | null;
            /** Artifact Uri */
            artifact_uri?: string | null;
            last_error?: components["schemas"]["StructuredError"] | null;
            /** Ambiguities */
            ambiguities?: components["schemas"]["Ambiguity"][];
            /** Clarifications */
            clarifications?: components["schemas"]["ClarificationQuestion"][];
        };
        /** SpecBody */
        SpecBody: {
            /** Expected Version */
            expected_version: number;
            factor_spec: components["schemas"]["FactorSpec-Input"];
        };
        /** StructuredError */
        StructuredError: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            category: components["schemas"]["ErrorCategory"];
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /**
             * Repairable
             * @default false
             */
            repairable: boolean;
        };
        /**
         * TimeConvention
         * @description The signal/trade timing contract carried by a spec, plan and artifact.
         *
         *     Defaults describe the首期 house convention: observe at the T close, treat it
         *     as knowable only after that close, form the signal on T, trade at the T+1
         *     open, and measure forward returns from that same open.
         */
        TimeConvention: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** @default T_CLOSE */
            observation_time: components["schemas"]["ObservationTime"];
            /** @default T_AFTER_CLOSE */
            information_available_time: components["schemas"]["InformationAvailableTime"];
            /**
             * Signal Date
             * @default T
             */
            signal_date: string;
            /**
             * Trade Date
             * @default T+1
             */
            trade_date: string;
            /** @default NEXT_OPEN */
            execution_price: components["schemas"]["ExecutionPrice"];
            /**
             * Forward Return Start
             * @default T+1_OPEN
             */
            forward_return_start: string;
            /**
             * Forward Return End
             * @default T+N_OPEN
             */
            forward_return_end: string;
            /** @default conservative */
            announcement_timing_policy: components["schemas"]["AnnouncementTimingPolicy"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationFinding */
        ValidationFinding: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            severity: components["schemas"]["ValidationSeverity"];
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
        };
        /** ValidationReport */
        ValidationReport: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Findings */
            findings?: components["schemas"]["ValidationFinding"][];
        };
        /**
         * ValidationSeverity
         * @enum {string}
         */
        ValidationSeverity: "error" | "warning" | "info";
        /** VersionBody */
        VersionBody: {
            /** Expected Version */
            expected_version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_formula_api_sessions__session_id__confirm_formula_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_fields_api_sessions__session_id__field_candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_fields_api_sessions__session_id__confirm_fields_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_manifest_api_sessions__session_id__manifest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_formula_api_sessions__session_id__revise_formula_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_fields_api_sessions__session_id__revise_fields_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_request_api_sessions__session_id__revise_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution_api_sessions__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_session_api_sessions__session_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloneBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_session_events_api_sessions__session_id__events_get: {
        parameters: {
            query?: {
                replay_only?: boolean;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
}
